Repository DevOps-Boot/fastapi-k8s, pull requests merged in 2023-11, with the labels that each got.

#36 Fixing branch, adding manual trigger
  .github/workflows/deploy_to_ecr.yaml
Labels: automation, cicd, application

#45 chore: create Docker and Traefik dedicated directories
  docker/Dockerfile
  docker/Dockerfile.prod
  docker/Dockerfile.traefik
  docker/docker-compose.prod.yml
  docker/docker-compose.yml
  traefik/traefik.dev.toml
  traefik/traefik.prod.toml
Labels: github

#69 Move to public registry
  .github/workflows/deploy_to_ecr.yaml
Labels: automation, cicd
